ln -s repo12/graduation/gym_malware/envs/controls/manipulate2.py 12m.py
ln -s repo13/graduation/gym_malware/envs/controls/manipulate2.py 13m.py
ln -s repo14/graduation/gym_malware/envs/controls/manipulate2.py 14m.py
ln -s repo15/graduation/gym_malware/envs/controls/manipulate2.py 15m.py
ln -s repo16/graduation/gym_malware/envs/controls/manipulate2.py 16m.py
ln -s repo17/graduation/gym_malware/envs/controls/manipulate2.py 17m.py
ln -s repo18/graduation/gym_malware/envs/controls/manipulate2.py 18m.py
ln -s repo19/graduation/gym_malware/envs/controls/manipulate2.py 19m.py
ln -s repo20/graduation/gym_malware/envs/controls/manipulate2.py 20m.py
ln -s repo21/graduation/gym_malware/envs/controls/manipulate2.py 21m.py
ln -s repo22/graduation/gym_malware/envs/controls/manipulate2.py 22m.py
ln -s repo23/graduation/gym_malware/envs/controls/manipulate2.py 23m.py
ln -s repo24/graduation/gym_malware/envs/controls/manipulate2.py 24m.py
ln -s repo25/graduation/gym_malware/envs/controls/manipulate2.py 25m.py
ln -s repo26/graduation/gym_malware/envs/controls/manipulate2.py 26m.py
ln -s repo27/graduation/gym_malware/envs/controls/manipulate2.py 27m.py
ln -s repo28/graduation/gym_malware/envs/controls/manipulate2.py 28m.py
ln -s repo29/graduation/gym_malware/envs/controls/manipulate2.py 29m.py
ln -s repo30/graduation/gym_malware/envs/controls/manipulate2.py 30m.py


ln -s repo1/graduation/models/ models1
ln -s repo2/graduation/models/ models2
ln -s repo3/graduation/models/ models3
ln -s repo4/graduation/models/ models4
ln -s repo5/graduation/models/ models5
ln -s repo6/graduation/models/ models6
ln -s repo7/graduation/models/ models7
ln -s repo8/graduation/models/ models8
ln -s repo9/graduation/models/ models9
ln -s repo10/graduation/models/ models10
ln -s repo11/graduation/models/ models11
ln -s repo12/graduation/models/ models12
ln -s repo13/graduation/models/ models13
ln -s repo14/graduation/models/ models14
ln -s repo15/graduation/models/ models15
ln -s repo16/graduation/models/ models16
ln -s repo17/graduation/models/ models17
ln -s repo18/graduation/models/ models18
ln -s repo19/graduation/models/ models19
ln -s repo20/graduation/models/ models20
ln -s repo21/graduation/models/ models21
ln -s repo22/graduation/models/ models22
ln -s repo23/graduation/models/ models23
ln -s repo24/graduation/models/ models24
ln -s repo25/graduation/models/ models25
ln -s repo26/graduation/models/ models26
ln -s repo27/graduation/models/ models27
ln -s repo28/graduation/models/ models28
ln -s repo29/graduation/models/ models29
ln -s repo30/graduation/models/ models30